name: Deploy Vertex AI Environment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Configure GCP credentials
      env:
        GCP_CREDS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "${GCP_CREDS}" > $HOME/gcloud.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Initialize Terraform
      working-directory: ./Terraform
      run: |
         terraform init -backend-config="credentials=$HOME/gcloud.json" \
                        -backend-config="bucket=terraform-123930" \
                        -backend-config="prefix=terraform-123930/state"

    - name: Validate Terraform
      working-directory: ./Terraform
      run: terraform validate

    - name: Plan Terraform
      working-directory: ./Terraform
      run: |
         terraform plan -var-file="main.tfvars" \
                        -var="project_id=${{ secrets.GCP_PROJECT_ID }}" \
                        -out=tfplan

    - name: Apply Terraform
      working-directory: ./Terraform
      run: |
         terraform apply -input=false -auto-approve tfplan
