name: Deploy Vertex AI Environment

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Configure GCP credentials
      env:
        GCP_CREDS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "${GCP_CREDS}" > $HOME/gcloud.json
        gcloud auth activate-service-account --key-file=$HOME/gcloud.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Plan Terraform
      working-directory: ./Terraform
      run: terraform plan -var "project_id=${{ secrets.GCP_PROJECT_ID }}" -out=tfplan

    - name: Apply Terraform
      working-directory: ./Terraform
      run: terraform apply -input=false tfplan
