name: Trigger Vertex AI Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch
    paths:
      - 'Vertex/**'
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  vertex-ai-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy and Run Vertex AI Pipeline
      working-directory: ./Vertex
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        LOCATION: us-central1
        GCP_CREDS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
      run: |

        echo "${GCP_CREDS}" > $HOME/gcloud.json
        export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcloud.json"
        gcloud auth activate-service-account --key-file=$HOME/gcloud.json
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

        python3 -m pip install setuptools

        python3 -m pip install -r requirements.txt


        python3 iris_pipeline.py  # Adjust this path if necessary

        gcloud ai pipelines upload --project=$PROJECT_ID --location=$LOCATION --display-name=iris-classification-pipeline --pipeline-file=pipeline/iris_pipeline.json
        gcloud ai pipelines run --project=$PROJECT_ID --location=$LOCATION --pipeline=iris-classification-pipeline --pipeline-root=gs://your-gcs-bucket/pipeline_root/ --job-id=iris_pipeline_run_$(date +%Y%m%d%H%M%S)
